### ISSUE TITLE
docker nginx

### ISSUE THREAD

**Issue by gear259** [fastogt/iptv_admin#9]
how do i resolve nginx port conflict error?

Creating nginx ... error

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (e049f5d91f81e996dea6498ebfb01efeeff21e27d0c888a5e8a38689990c6605): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (e049f5d91f81e996dea6498ebfb01efeeff21e27d0c888a5e8a38689990c6605): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by topilski** [comment]
In docker compose you can find this:
nginx:
```
        image: nginx
        container_name: nginx
        depends_on:
            - iptv_admin
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
- 80:80
```
